apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nginx-chart.labels" . | nindent 4 }}
data:
  nginx.conf: |
    {{- .Values.configmap.config | nindent 4}}