apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nginx-chart.labels" . | nindent 4 }}
    {{- if .Values.linkerd.inject }}
    linkerd.io/inject: "enabled"
    {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:      # etykiety, po których Deployment dopasowuje i kontroluje Pody
      {{- include "nginx-chart.selectorLabels" . | nindent 6 }}    
  template:
    metadata:
      labels:       # etykiety, które faktycznie zostaną nadane Podom; muszą zawierać wszystkie etykiety z selector.matchLabels
        {{- include "nginx-chart.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.ports.http }}
              protocol: TCP
          {{- with .Values.nginx.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.nginx.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
            - name: secret
              mountPath: {{ .Values.secrets.mountPath}}
              subPath: {{ .Values.secrets.subPath}}  
            - name: config
              mountPath: {{ .Values.configmap.mountPath}}
              subPath: {{ .Values.configmap.subPath}}  
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
      {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ default (include "nginx-chart.fullname" .) .Values.persistence.existingClaim }}
      {{- end }}
        - name: secret
          secret:
            secretName: {{ include "nginx-chart.fullname" .}}
        - name: config
          configMap:
            name: {{ include "nginx-chart.fullname" .}}
          
