apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-chart.fullname" . }}
  namespace: {{ .Values.namespace}}
  labels:
    {{- include "nginx-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: {{ .Values.service.ports.http }}
      protocol: TCP
      name: http
  selector:
      {{- include "nginx-chart.selectorLabels" . | nindent 6 }}